set(CPACK_PACKAGE_NAME "GitBolt")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_VENDOR "GitBolt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Fast cross-platform Git GUI client")

if(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_DMG_VOLUME_NAME "GitBolt")
elseif(WIN32)
    set(CPACK_GENERATOR "NSIS")
    set(CPACK_NSIS_DISPLAY_NAME "GitBolt")
    set(CPACK_NSIS_PACKAGE_NAME "GitBolt")
else()
    set(CPACK_GENERATOR "DEB;TGZ")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "GitBolt Team")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt6widgets6, libgit2-1.7")
endif()

include(CPack)
